services:
  rclone-storage:
    image: rclone/rclone:latest
    container_name: rclone-storage-in-rclone-webdav-example
    command: ["serve", "webdav", "/data", "--addr", ":8080"]
    ports:
      - "8080:8080"
    volumes:
      - ./webdav-data-for-rclone-webdav-example:/data
    restart: unless-stopped

  rclone-rc:
    image: rclone/rclone:latest
    container_name: rclone-rc-in-rclone-webdav-example
    depends_on:
      - rclone-storage
    command:
      - rcd
      - --rc-addr=:5572
      - --rc-no-auth
      - --rc-allow-origin=${RC_ALLOW_ORIGIN}
      - --log-level=INFO
      - --log-file=/logs/rclone.log
    ports:
      - "5572:5572"
    volumes:
      - ./rclone-config/webdav:/config/rclone
      - ./logs:/logs
    environment:
      - RCLONE_CONFIG=/config/rclone/rclone.conf
    restart: unless-stopped
